package com.java700.stewardship.reviews;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/** Pharmacist review task generated by time triggers, culture results or redundancy flags. */
@Entity
@Table(name = "review_tasks")
public class ReviewTask {

    public enum Status {
        OPEN, COMPLETED, CANCELLED
    }

    @Id
    @Column(name = "id", length = 36)
    private String id;

    @Column(name = "prescription_id", nullable = false, length = 36)
    private String prescriptionId;

    @Column(name = "trigger_reason", nullable = false, length = 64)
    private String triggerReason;

    @Column(name = "due_at", nullable = false)
    private Instant dueAt;

    @Column(name = "status", nullable = false, length = 16)
    private String status;

    @Column(name = "assigned_to", length = 120)
    private String assignedTo;

    @Column(name = "created_by", nullable = false, length = 120)
    private String createdBy;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    protected ReviewTask() {
    }

    public ReviewTask(String id, String prescriptionId, String triggerReason, Instant dueAt,
                      String createdBy, Instant createdAt) {
        this.id = id;
        this.prescriptionId = prescriptionId;
        this.triggerReason = triggerReason;
        this.dueAt = dueAt;
        this.status = Status.OPEN.name();
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    public String getId() {
        return id;
    }

    public String getPrescriptionId() {
        return prescriptionId;
    }

    public String getTriggerReason() {
        return triggerReason;
    }

    public Instant getDueAt() {
        return dueAt;
    }

    public Status getStatus() {
        return Status.valueOf(status);
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    void assign(String newPharmacist) {
        this.assignedTo = newPharmacist;
    }

    void complete(Instant at) {
        this.status = Status.COMPLETED.name();
        this.completedAt = at;
    }

    void cancel(Instant at) {
        this.status = Status.CANCELLED.name();
        this.completedAt = at;
    }
}
