# -*- coding: utf-8 -*-
# BLOCK 02p — Government / Compliance / Public Infrastructure (JAVA-696 .. JAVA-700) — Omega tier.
# NOTE: 45 additional Government/Public-Sector projects are cross-industry Omega projects
# in the JAVA-551..695 range tagged with a GovTech secondary industry.

ROWS = [
("Government / Justice", "Forensic evidence must be tracked with unbreakable chain-of-custody from seizure to court.", "Evidence ledger with hash chains, custody transfers, tamper detection and court-ready exports.", "Modular monolith; custody ledger; hash-chain service; transfer workflow; court export", "Spring Boot 3, Spring Security, Spring Data JPA, Flyway, MinIO SDK", "PostgreSQL 16, MinIO", "Kafka (custody events)", "RBAC, four-eyes transfers, hash-chain integrity, courtroom read-only roles", "Hash chaining, custody state machines, tamper alarms, exports", "Court-defensible custody with cryptographic integrity"),
("Government / Elections", "Electronic voting must be verifiable, auditable and resistant to tamper and coercion claims.", "Verifiable voting with ballot encryption sim, mix-net-style audit and independent tally verification.", "Modular monolith; ballot engine; audit trail; tally verifier; observer API", "Spring Boot 3, Spring Security, Spring Data JPA, Flyway", "PostgreSQL 16", "Kafka (vote events)", "Voter anonymity, ballot integrity hashes, observer read-only roles, audit", "End-to-end verifiability, tally proofs, coercion-resistance design", "Election-grade verifiability with independent audit"),
("Government / Emergency Mgmt", "Disaster warnings must reach citizens through multiple channels with geo-targeting and escalation.", "Early-warning hub with multi-channel fanout, geo-targeting, drill management and escalation.", "Modular monolith; alert engine; geo-targeter; channel fanout; drill scheduler", "Spring Boot 3, Spring Security, Spring Data JPA, Flyway", "PostgreSQL 16 (+PostGIS ext), Redis 7", "Kafka (alert events), MQTT (public channels)", "RBAC, emergency override roles, drill vs real separation, audit", "Geo-targeting, channel fanout, drills, escalation", "Life-safety-grade alerting with multi-channel reliability"),
("Government / Smart City", "City operations must be aggregated into a command-and-control view with cross-agency response.", "C2 aggregator with event correlation across agencies, resource tracking and unified dispatch.", "Modular monolith; event bus; correlation engine; resource registry; dispatch workflow", "Spring Boot 3, Spring Security, Spring Data JPA, Flyway, WebSocket", "PostgreSQL 16 (+PostGIS ext), Redis 7", "Kafka (city events)", "RBAC, agency isolation, incident confidentiality, audit", "Cross-agency correlation, resource tracking, dispatch", "City-grade command with cross-agency correlation"),
("Government / Identity", "Civil registries must record birth, marriage and death events immutably for a lifetime identity.", "CRVS with life-event state machines, document issuance, dedup and lineage integrity.", "Modular monolith; registry engine; life-event workflows; document service; dedup engine", "Spring Boot 3, Spring Security, Spring Data JPA, Flyway", "PostgreSQL 16, OpenSearch 2", "Kafka (life events)", "RBAC, registrar four-eyes, PII encryption, tamper-evident records", "Life-event state machines, dedup, document issuance", "Registry-grade identity with lifetime event integrity"),
]
