# -*- coding: utf-8 -*-
# BLOCK 1: project IDs + names + difficulty tiers.
# Tiers: 1 = Advanced (JAVA-001..100), 2 = Expert (101..250), 3 = Architect (251..400),
#        4 = Enterprise Platform (401..550), 5 = Omega (551..700)
# Counts: ENT=110, FIN=82, HLT=78, MFG=75, TEL=50, CYB=50, LOG=50, ENE=50, TRN=50, DAT=50, DEV=50, GOV=50, OMEGA=150 — but see
# OMEGA block: the Omega slab 551..700 absorbs the last 150 slots; category ledger below already nets the first 550.

ENT = []  # Enterprise Business Platforms — 110
for i in range(1, 111):
    ENT.append((f"JAVA-{i:03d}", "", 1 if i <= 100 else 2))

FIN = []  # Banking / FinTech / Insurance — 82
for i in range(111, 193):
    FIN.append((f"JAVA-{i:03d}", "", 2 if i <= 250 else 3))

HLT = []  # Healthcare / Pharma / Life Sciences — 78
for i in range(193, 271):
    HLT.append((f"JAVA-{i:03d}", "", 2 if i <= 250 else 3))

MFG = []  # Manufacturing / Industrial IoT / Robotics — 75
for i in range(271, 346):
    MFG.append((f"JAVA-{i:03d}", "", 3 if i <= 400 else 4))

TEL = []  # Telecom / Networking / Media Infrastructure — 50
for i in range(346, 396):
    TEL.append((f"JAVA-{i:03d}", "", 3 if i <= 400 else 4))

CYB = []  # Cybersecurity / Identity / Secrets — 50
for i in range(396, 446):
    CYB.append((f"JAVA-{i:03d}", "", 3 if i <= 400 else 4))

LOG = []  # Logistics / Supply Chain / Fleet — 50
for i in range(446, 496):
    LOG.append((f"JAVA-{i:03d}", "", 4))

ENE = []  # Energy / Utilities / Grid — 50
for i in range(496, 546):
    ENE.append((f"JAVA-{i:03d}", "", 4))

TRN = []  # Automotive / Aerospace / Transportation — 50  (IDs 546-595; 546-550 = Architect tier, 551-595 = Omega)
for i in range(546, 596):
    TRN.append((f"JAVA-{i:03d}", "", 4 if i <= 550 else 5))

DAT = []  # Data / AI Infrastructure — 50
for i in range(596, 646):
    DAT.append((f"JAVA-{i:03d}", "", 5))

DEV = []  # Developer / Platform Infrastructure — 50
for i in range(646, 696):
    DEV.append((f"JAVA-{i:03d}", "", 5))

GOV = []  # Government / Compliance / Public Infrastructure — 5 primary IDs (696-700), all Omega.
# The remaining 45 Government/Public-Sector projects are cross-industry Omega projects
# (IDs 551-695) that carry a GovTech secondary tag; category ledger = 50 total.
for i in range(696, 701):
    GOV.append((f"JAVA-{i:03d}", "", 5))

# ---------------------------------------------------------------------------
# OMEGA SLAB (JAVA-551..JAVA-700): the last 150 IDs are the Omega tier.
# They are drawn from the tail categories: TRN (551-595), DAT (596-645),
# DEV (646-695), GOV (696-700) — 45 of them also carry a GovTech secondary tag.


def fill(lst, names):
    out = []
    for (pid, _, tier), name in zip(lst, names):
        out.append((pid, name, tier))
    return out


ENT = fill(ENT, [
    "Workforce Compliance Evidence Platform",
    "Procure-to-Pay Reconciliation Platform",
    "Contract Lifecycle & Obligation Engine",
    "Enterprise Document Governance Vault",
    "Dynamic Workflow Orchestration Platform",
    "Audit-Grade Approval & Policy Chain Engine",
    "Legal Matter & Conflict Intelligence",
    "Expense Fraud & Policy Analytics Engine",
    "Fleet Maintenance Planning System",
    "Capacity & Shift Rostering Optimizer",
    "Vendor Risk & SLA Intelligence",
    "Training & Competency Evidence Manager",
    "Enterprise Search Across Policies & Records",
    "Assets & Depreciation Ledger Engine",
    "Recruitment Pipeline & Hiring Analytics",
    "Employee Offboarding & Access Revocation Engine",
    "Compensation Planning & Equity Ledger",
    "Time, Attendance & Labor Compliance Engine",
    "Payroll Rules Engine with Retro Calculation",
    "Benefit Elections & Life-Event Processing",
    "Corporate Travel Orchestration Platform",
    "Meeting Room & Workspace Reservation Engine",
    "Facilities Maintenance Command Center",
    "Lease Administration & Critical Dates Engine",
    "Energy Consumption & Sustainability Reporting",
    "Health, Safety & Incident Management System",
    "Insurance Policy Administration Suite",
    "Multi-Tenant SaaS Billing & Rating Engine",
    "B2B Supplier Collaboration Portal",
    "Channel Partner & Rebate Settlement Engine",
    "Enterprise Alerting & Escalation Engine",
    "Customer Master Data Management Hub",
    "Service Desk with SLA, Approval & Automation",
    "Software License Position & Entitlement Engine",
    "IT Change Advisory & Release Gate Board",
    "Onboarding Checklist & Day-1 Readiness Engine",
    "Employee Relocation & Mobility Management",
    "Internal Job Marketplace & Mobility Engine",
    "Enterprise Forms, Survey & Feedback Engine",
    "Content Moderation & Review Workflow Suite",
    "Field Service Dispatching & Optimization",
    "Print Shop Job Ticketing & Costing System",
    "Fitness Club Membership & Class Management",
    "Restaurant Chain Back-Office Operations Hub",
    "Retail Markdown & Promotion Optimization Engine",
    "Retail Store Replenishment & Allocation Engine",
    "Visual Merchandising & Planogram Compliance",
    "Customer Loyalty Ledger & Points Engine",
    "Gift Card Issuance, Ledger & Settlement",
    "Modern POS Back-Office & Tender Reconciliation",
    "Subscription & Dunning Management Platform",
    "Returns Management & Disposition Workflow",
    "Referral & Affiliate Attribution Engine",
    "Product Information Management Platform",
    "Dynamic Pricing Engine for B2B Quotes",
    "Catalog Syndication to Marketplace Channels",
    "E-Auction & Reverse Auction Platform",
    "RMA Diagnostics & Repair Parts Advisor",
    "Car Rental Reservation & Damage Claims",
    "Warehouse Slotting Optimization System",
    "Order Promise (ATP) Engine",
    "Demand Sensing & Forecast Reconciliation",
    "Production Planning & Finite Scheduling Engine",
    "Quality Non-Conformance & CAPA Platform",
    "Supplier Quality Scorecard & Audit Engine",
    "Procurement Sourcing Events & Bid Analytics",
    "Trade Promotion Management Platform",
    "Sales Territory, Quota & Compensation Engine",
    "Sales Forecasting with Opportunity Risk Scoring",
    "Call Center WFM: Forecasting & Scheduling",
    "Campaign Orchestration & Offer Decisioning",
    "Email Reputation & Deliverability Analytics",
    "Marketing Spend Attribution & Reconciliation",
    "Digital Asset Management with Rights Engine",
    "Event Management & Badge Security Platform",
    "Content Publishing Workflow & Editorial Calendar",
    "Job-Site Safety, Permits & Orientation System",
    "Subcontractor Progress & Payment Certification",
    "Equipment Rental & Utilization Marketplace",
    "Construction Materials & As-Built Traceability",
    "Tender Evaluation & Award Governance System",
    "Hotel Property Management Backbone",
    "Restaurant Table Flow & Kitchen Sync Engine",
    "Salon & Clinic Appointment Grid Engine",
    "Parking Operations & Enforcement Back-Office",
    "Mortgage Workflow & Document Checklist Engine",
    "Land & Property Records, Mutation & Deed Engine",
    "Lease Abstraction & Obligation Extraction Engine",
    "Museum Collection & Conservation Manager",
    "Library Consortium Circulation & Resource Sharing",
    "Arena, Stadium & Event Access Operations",
    "Talent Agency Rostering & Booking Platform",
    "Music Rights & Royalty Statement Engine",
    "Research Grant Lifecycle & Funding Governance",
    "R&D Idea Pipeline & Stage-Gate Management",
    "Patent & Invention Disclosure Docketing",
    "Laboratory Scheduling & Consumables Tracker",
    "Veterinary Practice Management Platform",
    "Farm Input, Yield & Traceability Ledger",
    "Call Center Quality Assurance & Scoring Engine",
    "B2B Credit Application & Underwriting Workbench",
    "Accounts Payable Invoice Automation",
    "Treasury Cash Forecasting & Positioning",
    "Enterprise Spend Analytics & Category Intelligence",
    "Travel & Expense Pre-Trip Compliance Engine",
    "Statutory Audit Sampling & Evidence Workbench",
    "Subsidiary Consolidation & Intercompany Engine",
    "Fixed Asset Tagging & Physical Audit Engine",
    "Robotic Process Automation Control Tower",
    "Complaint Resolution & Regulatory Response Tracker",
])

FIN = fill(FIN, [
    "Core Banking Ledger & Posting Engine",
    "Real-Time Payment Processing Hub",
    "International Wire Transfer Engine",
    "ACH Batch Processing & Returns Engine",
    "Card Transaction Authorization Switch",
    "Card Scheme Clearing & Settlement Engine",
    "Card Issuance & Token Vault Service",
    "Mobile Wallet & Money Movement Platform",
    "Recurring Payments & Mandate Engine",
    "Payment Reconciliation & Exceptions Workbench",
    "Payment Dispute & Chargeback Management",
    "Bank Statement & Notification Generator",
    "Digital Lending Origination Platform",
    "Loan Servicing & Delinquency Engine",
    "Amortization, Interest Accrual & Fee Engine",
    "Credit Decisioning & Policy Rules Engine",
    "Risk-Based Pricing & Limit Management",
    "Collections & Recovery Workflow Engine",
    "Debt Restructuring & Forbearance Engine",
    "Credit Bureau Reporting & Dispute Engine",
    "Anti-Money-Laundering Transaction Monitoring",
    "KYC Onboarding & Identity Verification Orchestrator",
    "Customer Screening Against Watchlists",
    "Sanctions & Regulatory Watchlist Update Engine",
    "Fraud Detection & Scoring Decision Service",
    "Fraud Case Management & SAR Filing Engine",
    "Insurance Underwriting Decision Platform",
    "Insurance Claims Intake & Straight-Through Processing",
    "Catastrophe Exposure & Reinsurance Engine",
    "Policy Renewal, Lapse & Grace Period Engine",
    "Actuarial Valuation & Reserve Calculation Engine",
    "Motor Claims: Accident Triage & FNOL",
    "Health Claims Adjudication & Pricing Engine",
    "Premium Billing, Collections & Dunning Engine",
    "Wealth Portfolio Rebalancing & Drift Engine",
    "Trading Risk Limits & Pre-Trade Checks",
    "Order Management & Smart Order Routing",
    "Market Data Tick Storage & Distribution",
    "Algo Backtesting & Paper Trading Lab",
    "P&L Attribution & Risk Analytics Service",
    "Derivative Lifecycle & Margin Engine",
    "Corporate Actions Processing Engine",
    "Settlement & Custody Reconciliation Engine",
    "Regulatory Reporting Data Pipeline (BCBS-style)",
    "Transaction Cost Analysis (TCA) Platform",
    "Market Abuse & Insider Trading Surveillance",
    "Digital Onboarding & eKYC Orchestrator",
    "Kiosk & Agent Banking Operations Hub",
    "SME Lending & Credit Guarantee Engine",
    "Microfinance Group Lending & Collections",
    "Peer-to-Peer Lending Marketplace",
    "Invoice Financing & Factoring Engine",
    "Supply Chain Finance & Dynamic Discounting",
    "Card Loyalty Points & Rewards Ledger",
    "Cashback Rules & Offer Settlement Engine",
    "Gift, Prepaid & Stored-Value Ledger",
    "Digital Gold & Commodity Accumulation Engine",
    "Remittance Corridor & FX Routing Engine",
    "Currency Exchange & Rate Management Desk",
    "Treasury Front Office Position & Hedge Engine",
    "Cash Pooling & Notional Netting Engine",
    "Interbank Messaging Gateway (SWIFT-style)",
    "ATM Monitoring & Cash Logistics Engine",
    "Branch Teller Capture & Proof System",
    "Card Fraud Rules Sandbox & Simulation",
    "Banking API Gateway & PSD2 Open Banking",
    "Consent & Data Sharing Permission Ledger",
    "Salary-On-Demand & Earned Wage Access",
    "Insurance Agent Commission & Hierarchy Engine",
    "Policy Administration & Product Factory",
    "Insurance Document & Clause Repository",
    "Reinsurance Treaty & Cession Calculation",
    "Financial Crime Graph & Link Analysis",
    "Behavioral Biometrics for Session Risk",
    "Document Forgery & Tamper Detection Service",
    "Beneficial Ownership & Structure Resolution",
    "Robo-Advisory Goal & Risk Profiling Engine",
    "Investment Performance & GIPS Reporting",
    "Risk Aggregation & Limit Monitoring Hub",
    "Fraud Network Scoring & Ring Detection",
    "Escrow & Multi-Party Settlement Service",
    "Tax Withholding & Reporting Calculator",
    "Ledger Reconciliation Bot Orchestrator",
])

HLT = fill(HLT, [
    "Patient Identity & Enterprise Master Index",
    "Admission, Transfer & Discharge Engine",
    "Appointment Scheduling & Waitlist Engine",
    "Clinical Document Generation & Sign-off",
    "Medication Orders & Dispensing Workflow",
    "Laboratory Order & Results Lifecycle",
    "Radiology Worklist & Report Distribution",
    "Care Plan Authoring & Task Engine",
    "Clinical Decision Support Rules Service",
    "Drug Interaction & Contraindication Checker",
    "Vaccination Registry & Cold-Chain Ledger",
    "Vitals Telemetry Ingestion & Trending",
    "Hospital Billing & Claims Scrubber",
    "Insurance Eligibility & Pre-Authorization",
    "Bed Management & Capacity Dashboard",
    "Operating Theater Scheduling & Utilization",
    "Emergency Triage & Patient Flow",
    "Infection Outbreak Surveillance & Alerts",
    "Antimicrobial Stewardship Tracker",
    "Blood Bank Inventory & Crossmatch",
    "Organ & Transplant Waitlist Registry",
    "Electronic Prior Authorization Engine",
    "Referral Management & Consult Workflow",
    "Remote Patient Monitoring Command",
    "Chronic Disease Registry & Cohort Care",
    "Physician Credentialing & Privileging",
    "Nurse Staffing & Acuity-Based Rostering",
    "Hospital Inventory & Consignment Pharmacy",
    "Dietary & Nutrition Management System",
    "Rehabilitation & Physiotherapy Tracker",
    "Mental Health Intake & Safety Assessment",
    "Pathology Specimen Tracking & Barcode",
    "Pharmacy Benefit Formulary & Tiering",
    "Clinical Trial Participant Recruitment",
    "Clinical Data Collection & Validation (EDC)",
    "Trial Safety Reporting & SAE Pipeline",
    "Regulatory Submission Publishing (eCTD-style)",
    "Drug Safety Pharmacovigilance Case Engine",
    "Signal Detection over Adverse Events",
    "Medical Coding Workbench (ICD/SNOMED-style)",
    "Data Anonymization & De-Identification Service",
    "Genomic Variant Interpretation Service",
    "Lab Instrument Data Integration Hub",
    "Sample Biobank & Consent Management",
    "Research Cohort Query & Phenotyping",
    "Synthetic Patient Data Generator",
    "Healthcare Interop Gateway (HL7/FHIR-style)",
    "FHIR Server & Resource Store",
    "Prescription E-Signature & Audit Chain",
    "Ambulance Dispatch & Crew Allocation",
    "Home Health Visit Scheduling & Routing",
    "Telemedicine Consultation & Queue Engine",
    "Medical Device Registry & Recalls",
    "Device Alerts & Alarm Fatigue Reducer",
    "Infusion Pump Programming Guardrails",
    "Patient Consent & Data Use Ledger",
    "Clinical Audit & Compliance Reviewer",
    "Health Scorecard & Quality Measures",
    "Wellness Program & Habit Nudging Engine",
    "Insurance Member Portal & Benefits Explainer",
    "Underwriting Health Risk Models Service",
    "Medical Claim Fraud & Abuse Detection",
    "Pharmacy Network & Reimbursement Engine",
    "Medication Therapy Management Platform",
    "Clinical Document De-Duplication & Mapper",
    "Care Team Collaboration & Secure Messaging",
    "Hospital Readmission Risk Predictor",
    "Discharge Summary & Aftercare Orchestrator",
    "Emergency Preparedness & Surge Planner",
    "Medical Coding Audit & DRG Grouper",
    "Clinical Terminology Server & Mapping",
    "Patient Feedback & Experience Analytics",
    "Dental Practice Imaging & Charting Hub",
    "Optometry Exam & Prescription Records",
    "Medical Equipment Maintenance & Calibration",
    "Clinical Guideline Repository & Versioning",
    "Health Data Lakehouse Ingestion Pipeline",
    "Wearable Data Integration & FHIR Mapping",
])

MFG = fill(MFG, [
    "Manufacturing Execution System (MES)",
    "Predictive Maintenance Intelligence Platform",
    "Digital Twin of a Production Line",
    "SCADA Gateway & Historian Replay",
    "Batch Recipe Management & Execution",
    "Overall Equipment Effectiveness (OEE) Analytics",
    "Statistical Process Control (SPC) Monitor",
    "Work Order Lifecycle & Labor Tracking",
    "Machine Downtime Tracking & Pareto Engine",
    "Tool Life & Cutter Wear Management",
    "CNC Program Versioning & Distribution",
    "Robot Cell Mission Orchestrator",
    "Quality Inspection Results & AQL Engine",
    "Non-Conformance & CAPA Workflow",
    "First Article Inspection (FAI) Package",
    "Materials Traceability & Genealogy Ledger",
    "Bill of Materials & Engineering Change Engine",
    "Configuration Management & Variant Explosion",
    "Shelf-Life & Expiry-Aware Inventory",
    "Kanban Replenishment & eKanban Boards",
    "Just-in-Time Sequencing & Line Feeding",
    "Yard Management & Dock Scheduling",
    "Returns & Refurbishment Line Planning",
    "Label Printing & Serialization Station",
    "Palletizing & Pack Pattern Optimizer",
    "Energy & Compressed-Air Consumption Analytics",
    "Emissions Monitoring & ESG Reporting",
    "Hazardous Material Handling & Storage",
    "Permit to Work & LOTO Safety System",
    "Shift Handover & Operator Logbook",
    "Operator Skills Matrix & Certification Ledger",
    "Standard Work Instructions & Digital Workbench",
    "Andon Escalation & Help Chain",
    "Error-Proofing (Poka-Yoke) Station Validation",
    "Defect Root-Cause Analysis Workspace",
    "FMEA & Risk Register Engine",
    "8D Problem-Solving Workflow",
    "Supplier Incoming Inspection & Skip-Lot",
    "Test Stand Orchestration & Result Broker",
    "Calibration Management & Recall Engine",
    "Gauge R&R Study Automation",
    "CMM & Metrology Data Management",
    "Shop-Floor Edge Gateway & Protocol Router",
    "Wireless Sensor Network Health Monitor",
    "Environmental Chamber Profile Control",
    "Manufacturing Costing & Variances Engine",
    "Capacity Rough-Cut Planning (RCCP)",
    "Sequencing Solver for Mixed-Model Lines",
    "Industrial Weighbridge & Catchweight",
    "Process Historian with Compression",
    "Alarm Rationalization & Flood Filtering",
    "Cobot Safety Zone & Speed Supervision",
    "AGV Fleet Traffic Management",
    "Additive Manufacturing Job Queue",
    "Surface Treatment & Plating Recipe Control",
    "Packaging Line Changeover Optimizer",
    "Serialization & Track-and-Trace (pharma grade)",
    "Warranty Claims & Field Quality Analytics",
    "Spare Parts Criticality & Reorder Engine",
    "RCM: Reliability-Centered Maintenance",
    "Maintenance Backlog & Shutdown Planner",
    "Work Permit Integration & Gas Testing",
    "Digital Work Order for Contractors",
    "Batch Genealogy & Recall Readiness",
    "Production Line Reconfiguration Simulator",
    "In-Plant Logistics Milk-Run Planner",
    "Smart Container & Bin Tracking",
    "Material Flow Simulation Sandbox",
    "Electronic Batch Record (EBR) Engine",
    "Set-Up Time Reduction (SMED) Planner",
    "Tool Crib & Vending Machine Inventory",
    "Thermal Process Profiling (reflow-style)",
    "Scrap & Yield Reconciliation Ledger",
    "Regulatory Audit Trail for Food Safety",
    "Food Safety HACCP Monitoring Platform",
])

TEL = fill(TEL, [
    "Subscriber Provisioning & SIM Lifecycle",
    "5G Network Slice Orchestrator (simulated)",
    "Cell Site Performance & KPI Analytics",
    "Fault & Alarm Correlation Engine",
    "Radio Access Capacity Planning",
    "Tower Lease & Colocation Billing",
    "VoIP Call Session Controller (SIP-style)",
    "SMS Gateway & Campaign Delivery Engine",
    "Number Portability & Routing Database",
    "OSS Inventory & Network Topology Store",
    "Configuration Drift & Compliance Scanner",
    "Bandwidth Policy & DPI Rule Provisioner",
    "CDN Request Routing & Cache Purge",
    "Video Transcoding Job Orchestrator",
    "Live Stream Playout & Ad Stitch Scheduler",
    "IPTV Channel Lineup & EPG Service",
    "Content Delivery Health & QoS Monitor",
    "Viewer Session & Concurrency Telemetry",
    "Digital Rights Enforcement Gateway",
    "Broadcast Playout & Schedule Engine",
    "Telecom Order Fulfillment Orchestrator",
    "Field Force Workforce Management (telco)",
    "Network Lab Environment Booking & Reset",
    "BGP Peer Health & Route Leak Detector",
    "Peering Settlement & Traffic Accounting",
    "Router Config Backup & Diff Auditor",
    "Spectrum Monitoring & Interference Mapper",
    "Fiber Plant GIS & Splice Records",
    "Cable Fault Localization Assistant",
    "Data Usage Metering & Fair-Use Engine",
    "Roaming Partner Settlement & TAP-style Files",
    "Voucher & Top-Up Batch Generation",
    "Fraudulent Call Pattern Detection",
    "SIM Box & Bypass Fraud Detector",
    "Location-Based Service & Geofence Engine",
    "Emergency Call Routing & Priority Handling",
    "Customer Experience Score Aggregator",
    "Broadband Speed Test Aggregation Service",
    "Mesh Network Self-Healing Coordinator",
    "IoT Device Provisioning for Operators",
    "Voicemail Platform & Transcription Queue",
    "Unified Comms Presence & Busy-Lamp Service",
    "Contact Center Routing Engine (telco)",
    "Trunk Capacity & Erlang-B Simulator",
    "Network Event Streaming & CEP Processor",
    "Service Activation & Test Harness",
    "Telecom Billing Mediation Pipeline",
    "Rating Engine for Usage Events",
    "Campaign SMS Shortcode Registry",
    "Call Detail Record Enrichment Pipeline",
])

CYB = fill(CYB, [
    "Enterprise Identity & Access Administration",
    "Identity Governance & Access Certification",
    "Privileged Access Management Vault",
    "Secrets Management & Rotation Service",
    "mTLS Certificate Lifecycle & Auto-Renewal",
    "Federated SSO & Session Boundary Broker",
    "OAuth Authorization Server & Token Engine",
    "Policy Decision Point (PDP) Service",
    "Zero Trust Session Risk Engine",
    "Password Manager with Breach Check",
    "MFA & TOTP Enrollment Orchestrator",
    "Credential Stuffing & Brute-Force Defense",
    "API Security Gateway & Schema Validator",
    "Web Application Firewall (WAF) Engine",
    "Rate-Limit & Traffic Shaping Service",
    "Bot Management & Human Verification",
    "DDoS Anomaly Detector (netflow-style)",
    "Intrusion Detection Log Analyzer",
    "Honeypot Deployment & Triage Console",
    "Threat Intelligence Feed Aggregator",
    "Vulnerability Scanner Orchestrator",
    "Vulnerability Lifecycle & SLA Tracker",
    "SBOM Generator & License Compliance",
    "Dependency Risk & CVE Mapper",
    "Container Image Security Scanner",
    "Runtime Application Self-Protection (RASP)",
    "Security Chaos Engineering Harness",
    "Phishing Simulation Campaign Engine",
    "Security Awareness Scoring Platform",
    "Insider Threat & UEBA Detector",
    "Digital Forensics Evidence Manager",
    "Incident Response Runbook Orchestrator",
    "Threat Hunting Query Workbench",
    "Security Data Lake Ingestion Pipeline",
    "SIEM Correlation Rule Engine",
    "SOAR Playbook Automation",
    "Audit Log Immutability & Chain Service",
    "Security Posture Scoring Engine",
    "Compliance Evidence Auto-Collector",
    "Data Classification & DLP Scanner",
    "Field-Level Encryption Gateway",
    "Data Masking & Tokenization Service",
    "Key Management Service (local HSM emulated)",
    "Signed Artifact & Release Verification",
    "Supply Chain Attestation Ledger",
    "Cloud-Native Policy-as-Code Auditor",
    "Network Micro-Segmentation Policy Engine",
    "Zero-Day Exploit Simulation Sandbox",
    "Biometric Liveness & Presentation-Attack Defense",
    "Secure Document Shredding & Retention Policy Engine",
])

LOG = fill(LOG, [
    "Transportation Management System",
    "Real-Time Shipment Visibility Platform",
    "Carrier Rate Shopping & Tender Engine",
    "Multi-Carrier Parcel Label Service",
    "Freight Audit, Payment & GL Coding",
    "Load Planning & 3D Palletization Engine",
    "Route Optimization & Daily Dispatch Engine",
    "Driver Hours-of-Service & ELD Rules",
    "Proof of Delivery & Exception Workflow",
    "Cold Chain Monitoring & Excursion Alerts",
    "Yard Management & Gate Automation",
    "Cross-Dock Scheduling & Sort Engine",
    "Last-Mile Delivery Slotting Engine",
    "Delivery Driver Marketplace & Payouts",
    "Drone Delivery Mission Planner (simulated)",
    "Warehouse Execution System",
    "Voice & Light-Directed Picking",
    "Returns Grading & Disposition Engine",
    "Customs Brokerage & HS Classification",
    "Duty & Tariff Calculation Engine",
    "Trade Compliance Screening (export controls)",
    "Document Set Generator for Shipments",
    "Incoterms & Cost Allocation Calculator",
    "Ocean Carrier Booking & Allocation",
    "Container Tracking & Demurrage Ledger",
    "Port Community & Vessel Turnaround",
    "Hinterland Rail Shuttle Planning",
    "Freight Forwarding Shipment Orchestrator",
    "NVOCC Consolidation & Deconsolidation",
    "Air Cargo ULD Build-Up Planning",
    "Ground Handling Slot & Resource Engine",
    "Dangerous Goods Validation & Placarding",
    "Parcel Sortation Machine Simulation",
    "Locker Network & PIN Distribution",
    "Package Exception Video & Photo Review",
    "Shipment Cost Allocation & P&L Engine",
    "Delivery Density Heatmap & Territory Engine",
    "Dynamic ETA Prediction Service",
    "Fleet Telematics Ingestion Hub",
    "Predictive Maintenance for Truck Fleets",
    "Fleet Compliance & Violation Ledger",
    "Asset Tracking with Geofence Events",
    "Reverse Logistics Network Design",
    "Fleet Electrification Charge Scheduling",
    "Intermodal Container Optimization",
    "Pallet Pool & Returnable Asset Tracking",
    "Warehouse Labor Standards & Incentives",
    "Loading Dock Appointment Booking",
    "Multi-Echelon Inventory Deployment",
    "Bulk Tanker Allocation & Scheduling",
])

ENE = fill(ENE, [
    "Smart Grid SCADA Event Processor",
    "Advanced Metering Infrastructure Headend",
    "Load Forecasting & Dispatch Planning",
    "Virtual Power Plant Aggregator",
    "Distributed Energy Resource Registry",
    "Microgrid Control & Islanding Engine",
    "Battery Storage Optimization (BESS)",
    "Electric Vehicle Charging Network Ops",
    "Demand Response Event Orchestrator",
    "Time-of-Use Tariff & Billing Engine",
    "Net Metering & Solar Credit Ledger",
    "Power Market Bidding & Settlement",
    "Renewable Production Forecasting (wind/solar)",
    "Wind Turbine Condition Monitoring",
    "Solar Plant Performance Analytics",
    "Grid Outage Management System (OMS)",
    "Distribution Automation & Switch Control",
    "Protection Relay Event Correlation",
    "Transformer Load & Health Analytics",
    "Substation Condition & Thermal Rating",
    "Energy Trading Desk & Position Engine",
    "Gas Pipeline Flow & Nominations",
    "Pipeline Leak Detection & Pressure Analytics",
    "LNG Terminal Berth & Regas Scheduling",
    "Oilfield Production Allocation Ledger",
    "Well Telemetry & Artificial Lift Monitor",
    "Tank Farm Inventory & Gauging Engine",
    "Refinery Blend Optimization & Lab Control",
    "Field Operator Rounds & Inspection App",
    "Workover Rig Scheduling & Logistics",
    "Power Plant Operations Logbook",
    "Outage Permit & Switching Order Engine",
    "Generator Dispatch & Unit Commitment",
    "Emissions Allowance & Carbon Ledger",
    "Utility Customer Service & Move-In Engine",
    "Meter Data Validation, Estimation & Editing",
    "Grid Event Playback & Forensic Replay",
    "Fault Location, Isolation & Service Restoration",
    "Crew Management & Storm Response",
    "Vegetation Management & Clearance Tracking",
    "Grid Asset Health & Reinvestment Planning",
    "Substation Commissioning Checklist Engine",
    "Energy Efficiency Audits & Retrofit Pipeline",
    "Utility Revenue Protection & Theft Analytics",
    "Smart City Lighting Control",
    "District Heating Network Optimization",
    "Hydro Plant Unit Efficiency Curves",
    "Nuclear Outage Work Package Manager",
    "Carbon Intensity Real-Time Display",
    "Peer-to-Peer Local Energy Trading",
])

TRN = fill(TRN, [
    "Automotive ECU Diagnostics Gateway (DoIP-style)",
    "Vehicle Telematics & Trip Analytics",
    "Connected Car OTA Update Campaigns",
    "Autonomous Vehicle Log Mining Lab",
    "ADAS Scenario Replay & Annotation",
    "Fleet Driver Safety Scoring",
    "Vehicle Recall & Campaign Manager",
    "Dealer Service Lane & Appointment Engine",
    "Warranty Analytics & Claim Adjudication",
    "Tire Pressure & Health Monitoring Service",
    "EV Battery Telemetry & Degradation Analytics",
    "Battery Swap Station Orchestrator",
    "Vehicle-to-Grid Session Ledger",
    "Ride-Hailing Dispatch & Matching Engine",
    "Dynamic Surge Pricing & Incentive Engine",
    "Carpool Matching & Trust Profiles",
    "Bus Network Planning & Headway Analysis",
    "Real-Time Transit Passenger Information",
    "Fare Collection & Capping Ledger",
    "Railway Signalling Simulation Workbench",
    "Rail Timetable Conflict Detection",
    "Rail Asset Condition & Track Geometry",
    "Rail Crew Duty & Fatigue Rules Engine",
    "Rolling Stock Maintenance Planner",
    "Train Dispatching & Delay Attribution",
    "Airline Revenue Management & Pricing",
    "Airline Schedule & Slot Coordination",
    "Aircraft Turnaround Orchestration",
    "Aircraft Maintenance Logbook & Deferrals",
    "MEL/CDL Configuration & Release",
    "Crew Pairing & Rostering Optimizer",
    "Airport Slot & Gate Allocation",
    "Baggage Reconciliation & Tracking",
    "Flight Data Monitoring & Exceedance Detector",
    "Air Traffic Flow Simulation (tower-lab)",
    "Maritime Vessel Tracking & AIS Processing",
    "Port Container Terminal Operations",
    "Ship Stowage & Stability Calculator",
    "Maritime Compliance & Port State Ledger",
    "Autonomous Underwater Inspection Missions",
    "Traffic Signal Coordination & Green Waves",
    "Road Congestion & Incident Detection",
    "Electronic Toll Collection & Enforcement",
    "Smart Parking Guidance Network",
    "Bicycle & Micro-Mobility Fleet Ops",
    "Hyperloop/Pod Scheduling Simulator",
    "Spacecraft Telemetry Ground Station",
    "Space Mission Planning & Constraint Engine",
    "Aircraft Spares Pooling & AOG Support",
    "Road Weather & Maintenance Decision Support",
])

DAT = fill(DAT, [
    "Data Ingestion & CDC Pipeline Orchestrator",
    "Data Quality Rules & SLA Engine",
    "Metadata Catalog & Data Lineage",
    "Master Data Management Registry",
    "Data Contract Enforcement Gateway",
    "Feature Store & Training Data Service",
    "Model Registry & Version Governance",
    "ML Experiment Tracking & Comparison",
    "Real-Time Model Serving & Drift Monitor",
    "Model Fairness & Bias Audit Toolkit",
    "ML Ops Deployment & Canary Engine",
    "Vector Search & Embedding Index Service",
    "Local RAG Pipeline & Document Q&A",
    "Entity Resolution & Deduplication",
    "Semantic Text Analytics & Classification",
    "Time-Series Anomaly Detection Engine",
    "Forecasting Service with Seasonality",
    "Recommendation Engine & Feedback Loop",
    "Churn Prediction & Retention Workbench",
    "NLP Entity Extraction & Redaction",
    "Batch Feature Backfill & Snapshotting",
    "Training Data Versioning & Lineage",
    "Hyperparameter Optimization Scheduler",
    "Model Explainability & SHAP-style Reports",
    "Streaming ML Inference Topology",
    "Data Masking for Non-Production",
    "Test Data Management & Synthesis",
    "Data Retention & Lifecycle Policer",
    "Query Federation & Virtual Data Catalog",
    "Real-Time Analytics with Materialized Views",
    "Metrics Aggregation & Rollup Service",
    "Data Warehousing ETL with Slowly Changing Dimensions",
    "Data Mesh Product Registry",
    "Schema Evolution & Compatibility Guardian",
    "Data Lineage & Impact Analysis",
    "Data Virtualization Security Layer",
    "Unstructured Document Extraction Pipeline",
    "OCR Post-Processing & Confidence Workbench",
    "Table Extraction & Tabular Data Structuring",
    "Graph Analytics & Path Query Service",
    "Geospatial Analytics & Heatmap Service",
    "Stream-to-Lakehouse Compaction Service",
    "Data Reliability & Freshness Monitor",
    "Self-Serve Analytics Workbench",
    "Embedding Cache & Inference Cost Governor",
    "Data Sampling & Statistical QA Service",
    "Event Schema Registry & Validation",
    "Data Product API & Access Billing",
    "Dark Data Discovery & Usage Metering",
    "Offline Data Sync for Field Devices",
])

DEV = fill(DEV, [
    "Internal Developer Portal & Catalog",
    "Service Catalog with Dependency Graphs",
    "Environment Provisioning & Teardown Engine",
    "Canary & Progressive Release Controller",
    "Feature Flag Platform with Targeting",
    "Distributed Config & Secret Injection",
    "Build Orchestration & Cache Manager",
    "Artifact Repository & Retention Policies",
    "Deployment Pipeline & Approval Gates",
    "Release Train & Version Management",
    "API Gateway & Traffic Manager",
    "API Developer Portal & Subscription Billing",
    "Schema Registry & Compatibility Gates",
    "Contract Testing Broker & Results",
    "Mock Service Virtualization Studio",
    "Load Testing Orchestration & Report Engine",
    "Chaos Experiment Scheduler",
    "Incident Management & On-Call Platform",
    "Status Page & Public Communication",
    "Runbook Automation Library",
    "SLO & Error Budget Tracker",
    "Alert Routing & Deduplication Engine",
    "Log Aggregation & Query Service",
    "Metrics Pipeline & Retention Tiering",
    "Trace Sampling & Storage Policy",
    "Profiling Data & Flamegraph Service",
    "Database Migration & Versioning Service",
    "Backup & Restore Orchestrator",
    "Capacity Forecasting & Rightsizing",
    "Cost Allocation & Showback Engine",
    "License Server & Usage Metering",
    "Self-Healing Remediation Agent",
    "Infrastructure Drift Detection",
    "Golden Image & AMI-style Factory",
    "DNS Zone & Record Lifecycle",
    "Certificate Auto-Renewal Bot",
    "Secrets Rotation Scheduler",
    "Network Policy & Firewall-as-Code",
    "Workspace Sandbox & IDE Environment Factory",
    "Code Review Bot & Policy Checker",
    "Static Analysis Aggregation & Quality Gates",
    "Tech Debt Ledger & Remediation Planner",
    "OpenAPI Lint & Breaking Change Detector",
    "Monorepo Build Graph & Affected Targets",
    "Test Impact Analysis & Flaky Test Quarantine",
    "Documentation Lint & Coverage Checker",
    "Internal CLI & Task Automation Hub",
    "SDK Generation & Client Release Pipeline",
    "Environment Parity Auditor",
    "Developer Experience Metrics & Surveys",
])

GOV = fill(GOV, [
    "Criminal Evidence Chain-of-Custody Ledger",
    "Electronic Voting with Verifiable Audit",
    "Disaster Early Warning & Alerting",
    "Smart City Command & Control Aggregator",
    "Digital ID & Civil Registry (CRVS)",
])

# --- NOTE: 45 additional Government/Public-Sector projects live inside the Omega slab
# (JAVA-551..JAVA-695) as cross-industry projects tagged with a GovTech secondary industry.
