spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:crvs}
    username: ${POSTGRES_USER:crvs}
    password: ${POSTGRES_PASSWORD:crvs}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:crvs}
    password: ${RABBIT_PASSWORD:crvs}

app:
  messaging:
    enabled: true
  seed:
    enabled: false

logging:
  structured:
    format:
      console: ecs
  level:
    com.java700.crvs: INFO
